import { Card, Col, Row } from "antd";
import React from "react";
import PageLayout from "../components/layouts/PageLayout";
import Profile from "../components/Profile";
import SEO from "../components/seo";
import e1 from "../images/training_camp.jpg";
import e2 from "../images/reliance.jpg";
import e3 from "../images/satyamev.jpeg";

export default () => (
  <PageLayout>
    <SEO title="Kudrati Kheti Gurukul" />

    <h1>Kudrati Kheti Gurukul</h1>

    <Row gutter={18}>
      <Col xs={24} md={12} lg={8}>
        <Profile
          designation=""
          image={e1}
        />
      </Col>
      <Col xs={24} md={12} lg={8}>
        <Profile
          designation=""
          image={e3}
        />
      </Col>
      <Col xs={24} md={12} lg={8}>
        <Profile
          designation=""
          image={e2}
        />
      </Col>
    </Row>

    <Card
      title=""
      bordered={false}
    >
      <p>
      It is a new initiative to promote organic farming. It is in initial phase. Funds for this initiative are generated by Satyamev Jayate and Reliance Foundation.</p>

<p>Reliance Foundation has set out to inspire and facilitate transformative change and build an inclusive India. The Foundation is working with some of the most marginalized communities nationwide with the objective of integrating them into the mainstream development process of India. Reliance Foundation works on the five core thrust areas of Rural Transformation, Education, Health, Urban Renewal and Arts , Culture & Heritage.
      </p>
    </Card>
  </PageLayout>
);
